[package]
name = "almost89/crayon"
description = "Don't bother with rich text. Based on Chalk."
license = "MIT"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
